// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIiSdsy07B4y9lJW60hstl2QLtERHZ3E0',
    appId: '1:1030004054709:web:04bc5084dd2444bb4dbcfc',
    messagingSenderId: '1030004054709',
    projectId: 'bookie-b932b',
    authDomain: 'bookie-b932b.firebaseapp.com',
    storageBucket: 'bookie-b932b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcYcRf5xSBZsX83pH3tqAsEIuy-EV1gWY',
    appId: '1:1030004054709:android:c08b1d0b5ee4b5be4dbcfc',
    messagingSenderId: '1030004054709',
    projectId: 'bookie-b932b',
    storageBucket: 'bookie-b932b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASLH-bWvR9TFl01_lTuri3Sp4lZ8HgoJE',
    appId: '1:1030004054709:ios:38cf75ab47b643504dbcfc',
    messagingSenderId: '1030004054709',
    projectId: 'bookie-b932b',
    storageBucket: 'bookie-b932b.firebasestorage.app',
    iosClientId: '1030004054709-s46t0edshp13q5384v03qlrblkheai34.apps.googleusercontent.com',
    iosBundleId: 'com.example.booksi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASLH-bWvR9TFl01_lTuri3Sp4lZ8HgoJE',
    appId: '1:1030004054709:ios:38cf75ab47b643504dbcfc',
    messagingSenderId: '1030004054709',
    projectId: 'bookie-b932b',
    storageBucket: 'bookie-b932b.firebasestorage.app',
    iosClientId: '1030004054709-s46t0edshp13q5384v03qlrblkheai34.apps.googleusercontent.com',
    iosBundleId: 'com.example.booksi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIiSdsy07B4y9lJW60hstl2QLtERHZ3E0',
    appId: '1:1030004054709:web:eab0c845da840c154dbcfc',
    messagingSenderId: '1030004054709',
    projectId: 'bookie-b932b',
    authDomain: 'bookie-b932b.firebaseapp.com',
    storageBucket: 'bookie-b932b.firebasestorage.app',
  );

}